CREATE OR REPLACE TABLE AIRLINES_DB.SILVER.TRANSFORMED_FLIGHT_TRACES AS
SELECT * EXCLUDE (_ROW_NUM)
FROM (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY ICAO, EVENT_TIMESTAMP
            ORDER BY EVENT_TIMESTAMP
        ) AS _ROW_NUM
    FROM AIRLINES_DB.SILVER.TRANSFORMED_FLIGHT_TRACES
)
WHERE _ROW_NUM = 1;
