CREATE TABLE IF NOT EXISTS AIRLINES_DB.BRONZE.FLIGHT_TRACES_RAW
(
    RAW_JSON VARIANT,
    SOURCE_FILE VARCHAR,
    DATA_DATE DATE,
    INGESTION_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO AIRLINES_DB.BRONZE.FLIGHT_TRACES_RAW (RAW_JSON, SOURCE_FILE, DATA_DATE)
FROM (
    SELECT
        $1,
        METADATA$FILENAME,
        '2026-04-26'::DATE
    FROM @traces_stage
)
PATTERN = '.*trace_full_.*\\.json'
FILE_FORMAT = (TYPE = 'JSON');
