SELECT
    DATA_DATE,
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT ICAO) AS UNIQUE_AIRCRAFT,
    COUNT(DISTINCT FLIGHT) AS UNIQUE_FLIGHTS,
    MIN(EVENT_TIMESTAMP) AS FIRST_EVENT,
    MAX(EVENT_TIMESTAMP) AS LAST_EVENT
FROM AIRLINES_DB.BRONZE.FLIGHT_TRACES
GROUP BY DATA_DATE
ORDER BY DATA_DATE;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(ICAO IS NULL) AS MISSING_ICAO,
    COUNT_IF(LAT IS NULL OR LON IS NULL) AS MISSING_POSITION,
    COUNT_IF(EVENT_TIMESTAMP IS NULL) AS MISSING_EVENT_TIMESTAMP
FROM AIRLINES_DB.BRONZE.FLIGHT_TRACES;

SELECT
    POSITION_TYPE,
    COUNT(*) AS RECORDS
FROM AIRLINES_DB.BRONZE.FLIGHT_TRACES
GROUP BY POSITION_TYPE
ORDER BY RECORDS DESC;
